### ISSUE TITLE
Re-tag as 4.x

### ISSUE THREAD

**Issue by chillu** [silverstripe/recipe-core#24]
@sminnee kicked this off in https://github.com/silverstripe/recipe-cms/issues/12#issuecomment-390154923. I agree that while some module releases vary in their release lines, it's generally more useful for the baseline recipe to track the "main release line" (4.x). It's also more consistent with how we handle installer. We should try to sort this before 4.2.0 comes out.

# PRs:

 - [x] https://github.com/silverstripe/silverstripe-admin/pull/542
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/792
 - [x] https://github.com/silverstripe/silverstripe-assets/pull/144
 - [x] https://github.com/silverstripe/silverstripe-versioned/pull/160
 - [x] https://github.com/silverstripe/silverstripe-reports/pull/101
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/8176
 - [x] https://github.com/silverstripe/silverstripe-graphql/pull/159
 - [x] https://github.com/silverstripe/silverstripe-errorpage/pull/23
 - [x] https://github.com/silverstripe/silverstripe-cms/pull/2190
 - [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/103

**Comment by chillu** [comment]
> Sam said: the recipe should have the same version numbers as framework, or more to the point, if someone says "I've installed SilverStripe version X.Y" that number should refer to the recipe version number. We should retag 1.x as 4.x.

I agree this should be the case for `recipe-core`. I could imagine where `recipe-cms` becomes decoupled from the core release lines, e.g. bumping `silverstripe/cms` to 5.x in a way that's compatible with `silverstripe/framework` on 4.x. That'll be crazy confusing to some, but is already the reality with new modules like `silverstripe/graphql`.

**Comment by tractorcow** [comment]
I would really rather not do this... We are leading back into self.version hell that took us a year to migrate away from.

That said I think the change is redundant and more confusing but shouldnt actually break anything.

**Comment by chillu** [comment]
A wild @tractorcow appears! Can you link to a discussion about this? So does cow assume all recipes are tagged with the same release line, and mixing those is an issue? That sounds like a missing feature, but would have short-term impacts. /cc @sminnee

**Comment by sminnee** [comment]
We haven't released SilverStripe 1.1. We've released SilverStripe 4.1. The version number of the recipe needs to match the "marketed version number" of SilverStripe. It's possible that in the future the version of _framework_ would drift away from this.

I'm not recommending that we include framework as a self.version dependency, simply that we correct the erroneous version number of this recipe file.

Otherwise we have instructions saying "To install SilverStripe 4.1 you should run composer installer silverstripe/recipe-rore:1.1" which is extremely confusing, and it's led to suggestions such as a major release of the recipe prior to a major release of SilverStripe, which would break support commitments and potentially led us down a very problematic path.

**Comment by sminnee** [comment]
To put it another way: The recipe "is SilverStripe" more than the framework module, and the version number needs to align with this.

**Comment by robbieaverill** [comment]
I agree with this. Recipes are the entry point for devs installing the software, so they should match the overall version of the product (at least the core ones should). For CWP we decided to create the new core CWP recipes for CWP 2 as 2.x rather than 1.x to keep this consistent.

It does raise a question about the new SilverStripe recipes that are optional: blog, content blocks, content authoring etc which are all in the 1.x line at the moment.

**Comment by sminnee** [comment]
OK so initially my view is that the recipe "is SilverStripe" and needs a version number to match. However really we have 3 different recipes:

 * installer
 * recipe-cms
 * recipe-core

The _installer_ is the recipe that "is SilverStripe" but there's a mash of responsibility between those 3.

The question comes down to: are we recommending that the community makes use of recipe-cms and recipe-core directly? If so, what do we call them? "SilverStripe CMS" and "SilverStripe Core Framework"? If you were calling them that, what version number would you attach in comms about it? The git tags needs to match those publicly communicated version.

**Comment by sminnee** [comment]
By way of comparison, if we made "SilverStripe Ecommerce Edition" and have recipe-ecommerce, we might rightly call this "SilverStripe Ecommerce Edition v1.0" even if it was based on framework:4.2. In that case tagging recipe-ecommece 1.0 would make sense (we do this with CWP) because our communicated version still matches the git tag.

**Comment by sminnee** [comment]
The only way I can see recipe-core and recipe-cms retaining a v1.0 tag as making sense is if we've never really intended them for public consumption.

**Comment by maxime-rainville** [comment]
I think there's a marketing consideration and and architectural consideration here. 

On the architectural side we should aimed to make each package decoupled from the others. In theory if `silverstripe/cms` 4.5 is compatible with the API of `silverstripe/framework` 4.1 then you should be able to have both those version run side by side if you want to. In practice, that doesn't seem to be the case yet ... that recent GraphQL change where we had to update 3 different repos to fix one thing is a good example.

On the marketing side, you will save yourself some confusion when you say that when installing SilverStripe 4.5, you're installing core 4.5, cms 4.5. That's the approach Symfony's taking I think. To be honest, I think that if we go down this road, we should go all in. e.g.: If Silverstripe/GraphQL is designed to work specifically with Framework 4.5, then it should be 4.5 as well.

**Comment by chillu** [comment]
> To be honest, I think that if we go down this road, we should go all in. e.g.: If Silverstripe/GraphQL is designed to work specifically with Framework 4.5, then it should be 4.5 as well.

That's not what we're aiming for, but rather what we're getting away from. This isn't about syncing release lines of modules, but rather of the `recipe/cms` and `recipe/core` with `silverstripe/framework`. Modules should not be tied to the (relatively long) cadence of core releases. I could see a graphql 3.x and 4.x iteration, which are both compatible with `silverstripe/framework` 4.x. These might not be part of a `recipe/core` 4.x release (under the proposed retagging, assuming we apply semver to recipes). But they might still be releases that devs can opt in to for getting more features and new APIs.

**Comment by maxime-rainville** [comment]
My preference would be to have no version sync at all.

However, it's not clear to me why arguments in favor of syncing recipe-core and recipe-cms with framework would not be equally valid for graphql, config, errorpage, etc.

**Comment by maxime-rainville** [comment]
I just like picking fights @chillu.

Which ever side of an issue he's on, I'll pick the opposite.  :stuck_out_tongue_winking_eye:

**Comment by sminnee** [comment]
One thing I should say: I'm not advocating for version syncing. `silverstripe/framework` might end up having its version number drift from the recipe. `silverstripe/framework` might eventually be deprecated in favour of a collection of mini-packages.

Rather, if there's one thing that should be marked with our publicly stated version, it should be the recipe, rather than the framework. As Ingo says "recipe/cms and recipe/core are stand-ins for 'the SilverStripe release line'"

**Comment by dhensby** [comment]
The thing is that the version of the recipes are completely arbitrary in a sense because they don't provide any APIs themselves so nothing the recipe changes can be "breaking". We'd just choose different version numbers almost as a way for users to specify how tight they want their version constraints.

If we moved to the recipe version being the SilverStripe version, I'd see the composer constraints following this kind of pattern:

silverstripe/core:4 -> silverstripe/framework:~4.0
silverstripe/core:4.0 -> silverstripe/framework:~4.0.0
silverstripe/core:4.0.0 -> silverstripe/framework:4.0.0

The precise versions would change from package to package but would be locked at various levels (as I see it) otherwise when do we decide a new release is needed or determine when the change should be a major change or a minor one?

**Comment by dhensby** [comment]
@sminnee I do partly agree with you that the recipes should, at least loosely, follow the "marketing" versions.

@flamerohr the point is that CWP is marketed as CWP 1 and CWP 2, it was never seen to be CWP 3...

**I wouldn't have any problem with us moving to using 4 as the version number for the recipes**

**Comment by chillu** [comment]
> A recipe's version seems arbitrary, e.g. cwp-core and cwp-recipe-core. Couldn't that have been re-numbered to be version 3 instead of 1 way back then as well? And how about retagging that as 4 for SilverStripe framework's version 4?

If you are a CWP dev, and you follow cwp.govt.nz instructions, your "API surface" is the CWP recipe, and that messaging is consistent: When we blog about "CWP 2.0 is released", the accompanying installation instructions say "composer require cwp/cwp:~2.0". It does include SilverStripe 4.0 with its own API surface and semver guarantees, but that's secondary here. Yes, you could argue that said CWP dev will still end up on doc.ss.org looking at SilverStripe 4 docs. But that pragmatic inconsistency (less docs duplication) is no reason to create *arbitrary and confusing versioning* for `silverstripe/recipe-core`.

So taking stock of opinions on retagging as 4.x (correct me if I'm getting it wrong):
- Yes: @sminnee, @chillu
- Maybe: @dhensby, @tractorcow, @flamerohr  (?)
- No: @maxime-rainville

Given the vote distribution above, I'm inclined to go ahead with this.

**Comment by maxime-rainville** [comment]
If `recipe-core` and `recipe-cms` become the main thing we market to people (as opposed to `cms` and `framework`), I would switch to _yes_.

**Comment by robbieaverill** [comment]
I don't mind either way. For me the important part is the compliance with semver in some way, which in this case is probably more around the contents of the packages that are in the recipe and how they change rather than actual code in each repo.

The semantics of v1 versus v4 doesn't bother me, it probably would've been good to start with 4.x from the get go but if it's going to be changed it should probably be done sooner rather than later =)

**Comment by maxime-rainville** [comment]
Sounds good. What would be the best way to communicate this to developers? I'm just thinking of those folks who have `~1.0` coded in their `composer.json`.

I presume the plan is to keep 1.0 and 1.1 and creating matching alias for 4.0 and 4.1?

Are we going to keep creating 1.x tags with matching 4.x tags until we hit SS5.0? Or are we going to stop tagging 1.x releases and only do 4.x from now on?

**Comment by robbieaverill** [comment]
`^1.0 || ^4.2` would probably be reasonable

**Comment by dhensby** [comment]
Could we put something in our recipe installer that would out put a warning when they see people using v1 tags for their recipes?

I think we should commit to maintaining the 1.x tags (which would be the same as 4.x tags) for a period of time whilst pushing some kind of deprecation notice to users (if we can) via composer.

**Comment by chillu** [comment]
@tractorcow mentioned that `cow` won't allow double tagging. Damian, can you detail if it's just a matter of running `cow` twice, or if there's substantial rewrites required? We might need to do one-off manual tagging for this one if that's the case.

Can anyone think of a way to get 4.2.0-rc1 out *before* doing this? My assumption is that this release work would also create an installer tag, which should contain those new 4.x recipe constraints.

**Comment by tractorcow** [comment]
You could setup separate branches, so you would do them as though they were separate releases.

However, you can't tag installer with the 1.x constraint because it already has a 4 branch. Installer 4.2.0 would only ever be able to point to recipe-cms of 1.2.0 or 4.2.0 only.

**Comment by tractorcow** [comment]
PRs created above.

**Comment by chillu** [comment]
Reflected in upgrader README through https://github.com/silverstripe/silverstripe-upgrader/pull/120
