### ISSUE TITLE
Branch numbers?

### ISSUE THREAD

**Issue by muppsy007** [silverstripe/recipe-core#36]
We've been testing a SS3-SS4 upgrade, starting by using the upgrade tool to "recompose", but this would still apply in cases where people are doing this manually.

It looks like at some point these recipes diverged from a single 1.x branch, to 4.x branch, and now there are differences between the two. 

The recompose tool (and likely people visiting this repo manually) see the default branch is now 4.x and update composer.json using that branch. Trouble is, some modules still use the old branching strategy for recipe requirements. Therefore, it's more likely that an upgrade will break. [silverstripe-opengraph](https://github.com/tractorcow/silverstripe-opengraph/blob/4.0.1/composer.json) is one example:

Site composer.json
`
"require": {
        "php": ">=5.6",
        "silverstripe/recipe-cms": "4.2.2",
        "silverstripe/recipe-core": "4.2.2"
    },
`

> composer update

`
Problem 1
    - tractorcow/silverstripe-opengraph 4.0.1 requires silverstripe/recipe-core ^1.0 -> satisfiable by silverstripe/recipe-core[1.0.0, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-rc1, 1.0.0-rc2, 1.0.0-rc3, 1.0.1, 1.0.1-rc1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.x-dev, 1.1.0, 1.1.0-rc1, 1.1.0-rc2, 1.1.1, 1.1.2, 1.1.3, 1.1.x-dev, 1.x-dev, 1.2.x-dev] but these conflict with your requirements or minimum-stability.
    - tractorcow/silverstripe-opengraph 4.0.0 requires silverstripe/recipe-core ^1.0 -> satisfiable by silverstripe/recipe-core[1.0.0, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-rc1, 1.0.0-rc2, 1.0.0-rc3, 1.0.1, 1.0.1-rc1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.x-dev, 1.1.0, 1.1.0-rc1, 1.1.0-rc2, 1.1.1, 1.1.2, 1.1.3, 1.1.x-dev, 1.x-dev, 1.2.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for tractorcow/silverstripe-opengraph ^4.0 -> satisfiable by tractorcow/silverstripe-opengraph[4.0.0, 4.0.1].
`

What is the actual branching strategy here?  Is the plan for 4.x to be the default branches and wait for module publishers to catch on and alter their requirements?

**Comment by maxime-rainville** [comment]
# Short answer:
The numbering version of recipe-core and recipe-cms went through a bit of an evolution a couple months ago. 

Developers should target the 4.x recipes.

# Long answer
`recipe-core` and `recipe-cms` were originally tag as version `1.x`. Around the SilverStripe 4.2 release we came to the conclusion that this would be confusing. e.g.: To install SilverStripe 4.2 you need to install recipe-cms 1.2.

So we decided to retarget the version of recipe-core and recipe-cms to version 4. We manually created 4.0 and 4.1 tags so projects could target `silverstripe/recipe-core:^4.0`. Going forward we will manually create 1.x aliases for all the 4.x release of recipe-core and recipe-cms. So projects targeting `recipe-core: ^1.0` will keep working.

Unfortunately if a module targets recipe-core 1.0 and your project targets recipe-core 4.0, you will get  conflicts. Modules should probably target the specific packages they need rather than target a specific recipe. 

The specific package in your example [was updated to support support both the 1.x and 4.x branch](https://github.com/tractorcow/silverstripe-opengraph/commit/f701656dc3d2b71528d069237e89e87c2df3d375), so it should be working. 

Maybe try removing your vendor folder and running a composer update.

# Very long answer with blow-by-blow drama
https://github.com/silverstripe/recipe-core/issues/24

**Comment by ScopeyNZ** [comment]
To be fair the update in that package that you mentioned is not tagged stable yet 🙂 . Maybe @tractorcow would be nice enough to do that for you (and maybe merge the PR that's open too)?

**Comment by muppsy007** [comment]
@maxime-rainville @ScopeyNZ @robbieaverill Thanks for the detailed info. That last part about avoiding the use of recipes in module dependencies is very handy.

**Comment by maxime-rainville** [comment]
I think the core questions has been answered. I'll close this issue as there's nothing for us to action, but feel free to keep the conversation going if you want more details.
