### ISSUE TITLE
Update _config.php note or code regarding "PasswordValidator for SilverStripe 5.0"

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/recipe-core#84]
There's a note in `_config.php` to "remove PasswordValidator for SilverStripe 5.0"
https://github.com/silverstripe/recipe-core/blob/054ce0e5f00926f75202e139eaaea1973c8da98a/app/_config.php#L6-L9

This was added in https://github.com/silverstripe/recipe-core/pull/35, which provides _some_ additional context. I _think_ the implication is that removing those lines for CMS 5 won't change anything.

## Acceptance criteria
- [x] Validate that removing those two lines doesn't change any behaviour
- [x] If those lines can be removed with no change to behaviour, remove them - and the file with them as nothing else is happening there.
- [ ] If those lines _cannot_ be removed without altering behaviour, update the comments to make it clearer why these lines are here.

@robbieaverill as the person who added those lines do you have any additional context as to what the intention was here, and whether it should be safe to remove?

## PRs
- https://github.com/silverstripe/recipe-core/pull/86

**Comment by robbieaverill** [comment]
Hi @GuySartorelli, I don't remember, sorry. There is a decent amount of context here: https://github.com/silverstripe/cwp-core/issues/52. I think possibly the "remove in 5.0" comment might have been some optimism around configuring the Member default password validator in YAML rather than PHP for that version, but can't be sure.

**Comment by GuySartorelli** [comment]
PR merged
